# Generated by Django 4.2.3 on 2023-07-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MelodySync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
