# Generated by Django 4.2.3 on 2023-07-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MelodySync', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_created',
        ),
    ]
