# Generated by Django 4.2.3 on 2023-07-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MelodySync', '0003_remove_user_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
